version: '3'
services:
  web:
    image: translator-web
    build: .
    ports:
      - "8000:8000"
    environment:
      - LIBRE_TRANSLATE_URL=http://libretranslate:5000/translate
      - APP_DIRECTORY=/app
      - LIBRE_TRANSLATE_PORT=8000
    volumes:
      - ./app:/app
      - /foreign_files:/foreign_files
    depends_on:
      - libretranslate
  libretranslate:
    image: libretranslate/libretranslate
    volumes:
      - /input:/input
      - /output:/output
      - libretranslate_lang_files:/home/libretranslate/.local
volumes:
  libretranslate_lang_files: