version: '3'
services:
  
  web-dev:
    image: translator.dev
    build:
      context: ./
      dockerfile: Dockerfile
      target: dev
    environment:
      - LIBRE_TRANSLATE_URL=http://libretranslate:5000/translate
      - APP_DIRECTORY=/app
      - LIBRE_TRANSLATE_PORT=8001
    volumes:
      - ./:/app
      - ./foreign_files:/foreign_files
    networks:
      - kafka_net
  

# Networks ================================================
networks:
  kafka_net:
    name: kafka_net