services:
  
  web-dev:
    image: translator.dev
    build:
      context: ./
      dockerfile: Dockerfile
      target: dev
    env_file:
      - .env
    volumes:
      - ./:/app
      - ./foreign_files:/foreign_files
    depends_on:
      - libretranslate      
    networks:
      - kafka_net
  

  libretranslate:
    image: libretranslate/libretranslate
    volumes:
      - input:/input
      - output:/output
      - libretranslate_lang_files:/home/libretranslate/.local
    ports:
      - "5000:5000"
    environment:
      - LT_DEBUG=True
      - LT_FRONTEND_LANGUAGE_TARGET=en
    networks:
      - kafka_net
      

volumes:
  input:
  output:
  libretranslate_lang_files:



# Networks ================================================
networks:
  kafka_net:
    name: kafka_net